### ISSUE TITLE
Collected data is not transported when network plugin is used

### ISSUE THREAD

**Issue by francispereira** [powdahound/redis-collectd-plugin#10]
We write to network using network and write_http. The collected data is never send out over the wire. I am pretty certain about this because I am dumping the whole request on the server where write_http is configured to send data in JSON format. 

redis_info appears to be configured correctly  - I can see lines in syslog that say 'collectd[22976]: redis plugin [verbose]: Sending value: connections_received=433'

**Comment by powdahound** [comment]
Hmm, it is collectd's job to take the output from various plugins and deliver them to your configured endpoints. This plugin simply calls the `dispatch()` method provided by the collectd python lib ([doc](https://collectd.org/documentation/manpages/collectd-python.5.shtml)). Is your issue unique to this plugin? Might want to check #collectd IRC or the mailing list.

**Comment by francispereira** [comment]
This issue is unique to the redis / python plugin only. I have plugin uptime running as well, its data is successfully transported over the wire in JSON format by write_http to the configured endpoint

**Comment by powdahound** [comment]
Odd. I'm not in a position to help debug this right now as I'm not actively using collectd. Can you try their IRC or mailing list? I suspect its an issue with the python plugin since this script is just using its published methods as documented.

**Comment by francispereira** [comment]
This looks related to https://github.com/collectd/collectd/issues/716
