### ISSUE TITLE
Possibility of monitoring multiple redis instances?

### ISSUE THREAD

**Issue by danfinn** [powdahound/redis-collectd-plugin#11]
We run multiple redis instances on each server.  Is it possible to use this plugin to collects stats from multiple instances on the same machine?  I tried configuring it a couple of different ways in collectd.conf but none seemed to work.  I do have it working for a single instance and that works quite well, now I just need to figure out how to get metrics from all the rest.

**Comment by powdahound** [comment]
I *think* you can just load the `<Module redis_info>` block multiple times. Did that not work?

**Comment by danfinn** [comment]
I'm loading it as follows and it doesn't seem to work, it only ever creates redis_info directory on the graphite server for this host

<Plugin python>
  ModulePath "/var/lib/collectd/plugins/python"
  Import "redis_info"

  <Module redis_info>
    Host "127.0.0.1"
    Port 6000
    Verbose false
  </Module>

  <Module redis_info>
    Host "127.0.0.1"
    Port 6001
    Verbose false
  </Module>

  <Module redis_info>
    Host "127.0.0.1"
    Port 6002
    Verbose false
  </Module>

</Plugin>

**Comment by powdahound** [comment]
Hmm - I thought that was the right way. Hey @zsiddique what's your config show for this setup?

**Comment by garyelephant** [comment]
This merge #12 solve this problem.

**Comment by akerekes** [comment]
Would it be possible to explicitly define ```plugin_instance```? With this automated assignment, the name of the metric contains the hostname. 
In our case this recent change causes issues. We use Librato where you can add metrics to a chart and it can distinguish between metric values based on their source. Until now we had to include one metric: ```collectd.redis_info.counter.commands_processed``` and based on the source we have received multiple lines on the same chart. Also adding and removing sources did not required any change in Librato.
Now if we add a metric with the hostname and port in it, it has to be maintained if the sources change.

A change that would allow explicit plugin_instance value with possible empty string as a config option that defaults to the hostname:port value if not specified would be helpful.

**Comment by powdahound** [comment]
Seems very reasonable. I'm not in a position to implement and test a new config option for the instance name but would happily accept a simple PR adding it.

**Comment by akerekes** [comment]
@powdahound I've created #13 to address this.

**Comment by garyelephant** [comment]
@akerekes a great enhancement

**Comment by powdahound** [comment]
Thanks! And thank you for updating the README very nicely too.
