### ISSUE TITLE
How to access multi-value/dict keys

### ISSUE THREAD

**Issue by willhughes** [powdahound/redis-collectd-plugin#19]
I'm trying to figure out how to access the multi-value/dict keys. 

Looking at the source it seems you are parsing out multi-value keys, but not actually making them accessible. 

I've tried the following: 

    Redis_db0_keys 
    Redis_db0["keys"]
    Redis_db0 

The first two fail, the third gives an error message saying it doesn't expect a dict value. 

Any suggestions?

**Comment by powdahound** [comment]
Doh - looks like this broke with #16. Someone even left a comment there after that I missed. @deimosfr - are you not tracking key count on your instances?

**Comment by willhughes** [comment]
Any chance this might get addressed? I'm not competent enough in Python to provide a fix myself.

**Comment by powdahound** [comment]
I'll take a look sometime in the next week and see what the scope of the
fix would be.

**Comment by powdahound** [comment]
^ See the commit above.

I don't have time to set up a test install of collectd and redis to test this properly, so I'm hoping you can give it a shot and let me know how it goes. You can now use the `Redis_db0_keys` format in the config (see updated README in the above change).

**Comment by willhughes** [comment]
Hey, thanks for your help. 

Unfortunately something is broken, even without using that key, I get this message: 

Here's the collectd log: 

[2015-11-10 00:27:54] Initialization complete, entering read-loop.
[2015-11-10 00:27:54] Unhandled python exception in read callback: TypeError: string indices must be integers, not str
[2015-11-10 00:27:54] read-function of plugin `python.redis_info' failed. Will suspend it for 2.000 seconds.


Funnily this looks kinda like the hacking I did thinking I could get it to go - I gave up with a similar error message.

**Comment by powdahound** [comment]
Try that one. :)

**Comment by willhughes** [comment]
Yep, that works - thanks a bunch!

**Comment by powdahound** [comment]
Great! Thanks for testing these. I've merged the fix into master.
