### ISSUE TITLE
Multiple Instance monitoring not sending date

### ISSUE THREAD

**Issue by aflatto** [powdahound/redis-collectd-plugin#21]
When configuring several instances of redis on the same box with multiple  <Module> definitions for each  instance, but it seem that it is not sending any data to the Graphite server.

The log file does not show me any errors .

Also is there a way to alter the output string to match the convention we have ? (our TLD metric name is "Linux." not "colllectd" )

Oct 11 01:35:38 ic-01 collectd[30649]: Initialization complete, entering read-loop.
Oct 11 01:35:54 ic-01 collectd[30649]: Exiting normally.
Oct 11 01:35:54 ic-01 collectd[30649]: collectd: Stopping 5 read threads.
Oct 11 01:35:54 ic-01 collectd[30649]: collectd: Stopping 5 write threads.
Oct 11 01:36:09 ic-01 collectd[30666]: plugin_load: Could not find plugin "disk" in /usr/lib64/collectd
Oct 11 01:36:09 ic-01 collectd[30666]: Found a configuration for the `disk' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Oct 11 01:36:09 ic-01 collectd[30666]: Found a configuration for the `disk' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Oct 11 01:36:09 ic-01 collectd[30666]: Initialization complete, entering read-loop.
Oct 11 01:37:21 ic-01 collectd[30666]: Exiting normally.
Oct 11 01:37:21 ic-01 collectd[30666]: collectd: Stopping 5 read threads.
Oct 11 01:37:21 ic-01 collectd[30666]: collectd: Stopping 5 write threads.

Disk configuration :
LoadPlugin disk

<Plugin disk>
        Disk "/^[hs]d[a-f][0-9]?$/"
        IgnoreSelected false
</Plugin>

oddly this plugin is not shipped with my version of collectd : collectd-5.5.0.189

**Comment by powdahound** [comment]
Can you post your config?

Also, because you're having issues with the `disk` plugin, perhaps none of the plugins are being loaded and no data is being collected? I don't remember how collectd behaves in this case.

> oddly this plugin is not shipped with my version of collectd : collectd-5.5.0.189

Are you referring to this redis plugin? It's unofficial. See https://collectd.org/wiki/index.php/Redis

**Comment by aflatto** [comment]
Hello,

This is the collectd.conf config file


[root@dal09-ic-01 ~]$ cat /etc/collectd.conf
# THIS FILE HAS BEEN GENERATED BY CHEF
# ANY MANUAL MODIFICATIONS WILL BE OVERWRITTEN
#
# Config file for collectd(1).
# Please read collectd.conf(5) for a list of options.
# http://collectd.org/
#

##############################################################################
# Global #
#----------------------------------------------------------------------------#
# Global settings for the 
daemon.                                            #
##############################################################################

Hostname     ic-01
#FQDNLookup   true
#BaseDir     "/usr/var/lib/collectd"
#PIDFile     "/usr/var/run/collectd.pid"
PluginDir   "/usr/lib64/collectd"
#TypesDB     "/usr/share/collectd/types.db"
#Include       "/etc/collectd.d/*.conf"
#Interval     10
#Timeout      2
#ReadThreads  5

##############################################################################
# Logging #
#----------------------------------------------------------------------------#
# Plugins which provide logging functions should be loaded first, so 
log     #
# messages generated when loading or configuring other plugins can 
be        #
# accessed. #
##############################################################################

LoadPlugin syslog
#LoadPlugin logfile

#<Plugin logfile>
#       LogLevel info
#       File STDOUT
#       Timestamp true
#       PrintSeverity false
#</Plugin>

#<Plugin syslog>
#       LogLevel info
#</Plugin>

##############################################################################
# LoadPlugin 
section                                                         #
#----------------------------------------------------------------------------#
# Lines beginning with a single `#' belong to plugins which have been 
built  #
# but are disabled by 
default.                                               #
# #
# Lines begnning with `##' belong to plugins which have not been built 
due   #
# to missing dependencies or because they have been deactivated 
explicitly.  #
##############################################################################

LoadPlugin cpu
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin redis
LoadPlugin write_graphite

##############################################################################
# Plugin configuration #
#----------------------------------------------------------------------------#
# In this section configuration stubs for each plugin are provided. A 
desc-  #
# ription of those options is available in the collectd.conf(5) manual 
page. #
##############################################################################

#<Plugin apache>
#  <Instance "local">
#    URL "http://localhost/status?auto"
#    User "www-user"
#    Password "secret"
#    CACert "/etc/ssl/ca.crt"
#  </Instance>
#</Plugin>

<Plugin disk>
         Disk "/^[hs]d[a-f][0-9]?$/"
         IgnoreSelected false
</Plugin>

#<Plugin dns>
#       Interface "eth0"
#       IgnoreSource "192.168.0.1"
#       SelectNumericQueryTypes true
#</Plugin>


#<Plugin mysql>
#       <Database db_name>
#               Host "database.serv.er"
#               User "db_user"
#               Password "secret"
#               Database "db_name"
#               MasterStats true
#       </Database>
#
#       <Database db_name2>
#               Host "localhost"
#               Socket "/var/run/mysql/mysqld.sock"
#               SlaveStats true
#               SlaveNotifications true
#       </Database>
#</Plugin>

#<Plugin nginx>
#       URL "http://localhost/status?auto"
#       User "www-user"
#       Password "secret"
#       CACert "/etc/ssl/ca.crt"
#</Plugin>

#<Plugin ntpd>
#       Host "localhost"
#       Port 123
#       ReverseLookups false
#</Plugin>

#<Plugin ping>
#       Host "host.foo.bar"
#       Interval 1.0
#       Timeout 0.9
#       TTL 255
#       SourceAddress "1.2.3.4"
#       Device "eth0"
#       MaxMissed -1
#</Plugin>

<Plugin redis>
    <Node "ImageCache_00">
       Host "localhost"
       Port "7777"
       Timeout 2000
    </Node>
    <Node "ImageCache_13">
       Host "localhost"
       Port "7778"
       Timeout 2000
    </Node>
    <Node "ImageCache_26">
       Host "localhost"
       Port "7779"
       Timeout 2000
    </Node>
    <Node "ImageCache_39">
       Host "localhost"
       Port "7780"
       Timeout 2000
    </Node>
    <Node "ImageCache_4C">
       Host "localhost"
       Port "7781"
       Timeout 2000
    </Node>
    <Node "ImageCache_5F">
       Host "localhost"
       Port "7782"
       Timeout 2000
    </Node>
    <Node "ImageCache_72">
       Host "localhost"
       Port "7783"
       Timeout 2000
    </Node>
    <Node "ImageCache_85">
       Host "localhost"
       Port "7784"
       Timeout 2000
    </Node>
    <Node "ImageCache_98">
       Host "localhost"
       Port "7785"
       Timeout 2000
    </Node>
    <Node "ImageCache_AB">
       Host "localhost"
       Port "7786"
       Timeout 2000
    </Node>
</Plugin>

<Plugin write_graphite>
   <Node "ic-01">
     Host "graphite"
     Port "2003"
     Protocol "tcp"
     LogSendErrors true
     Prefix "Linux."
     StoreRates true
     AlwaysAppendDS false
     EscapeCharacter "_"
   </Node>
</Plugin>


##############################################################################
# Filter configuration #
#----------------------------------------------------------------------------#
# The following configures collectd's filtering mechanism. Before 
changing   #
# anything in this section, please read the `FILTER CONFIGURATION' 
section   #
# in the collectd.conf(5) manual 
page.                                       #
##############################################################################

# Load required matches:
#LoadPlugin match_empty_counter
#LoadPlugin match_hashed
#LoadPlugin match_regex
#LoadPlugin match_value
#LoadPlugin match_timediff

# Load required targets:
#LoadPlugin target_notification
#LoadPlugin target_replace
#LoadPlugin target_scale
#LoadPlugin target_set
#LoadPlugin target_v5upgrade

#----------------------------------------------------------------------------#
# The following block demonstrates the default behavior if no filtering 
is   #
# configured at all: All values will be sent to all available write 
plugins. #
#----------------------------------------------------------------------------#

#<Chain "PostCache">
#  Target "write"
#</Chain>

##############################################################################
# Threshold 
configuration                                                    #
#----------------------------------------------------------------------------#
# The following outlines how to configure collectd's threshold 
checking      #
# plugin. The plugin and possible configuration options are documented 
in    #
# the collectd-threshold(5) manual 
page.                                     #
##############################################################################

#LoadPlugin "threshold"
#<Plugin "threshold">
#  <Type "foo">
#    WarningMin    0.00
#    WarningMax 1000.00
#    FailureMin    0.00
#    FailureMax 1200.00
#    Invert false
#    Instance "bar"
#  </Type>
#
#  <Plugin "interface">
#    Instance "eth0"
#    <Type "if_octets">
#      FailureMax 10000000
#      DataSource "rx"
#    </Type>
#  </Plugin>
#
#  <Host "hostname">
#    <Type "cpu">
#      Instance "idle"
#      FailureMin 10
#    </Type>
#
#    <Plugin "memory">
#      <Type "memory">
#        Instance "cached"
#        WarningMin 100000000
#      </Type>
#    </Plugin>
#
#    <Type "load">
#       DataSource "midterm"
#       FailureMax 4
#       Hits 3
#       Hysteresis 3
#    </Type>
#  </Host>
#</Plugin>

and this is the plugin config file :

# Configure the redis_info-collectd-plugin

<LoadPlugin python>
   Globals true
</LoadPlugin>

<Plugin python>
   ModulePath "/usr/lib64/collectd/"
   Import "redis_info"

   <Module redis_info>
     Host "localhost"
     Port 7777
     Instance "ImageCache_00"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7778
     Instance "ImageCache_13"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7779
     Instance "ImageCache_26"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7780
     Instance "ImageCache_39"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7781
     Instance "ImageCache_4C"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7782
     Instance "ImageCache_5F"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7783
     Instance "ImageCache_72"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7784
     Instance "ImageCache_85"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7785
     Instance "ImageCache_98"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
   <Module redis_info>
     Host "localhost"
     Port 7786
     Instance "ImageCache_AB"
     # Un-comment to use AUTH
     #Auth "1234"
     Verbose false
     # Catch Redis metrics (prefix with Redis_)
     Redis_lru_clock "counter"
     Redis_evicted_keys "gauge"
     Redis_used_memory "bytes"
     Redis_used_memory_peak "bytes"
     Redis_changes_since_last_save "gauge"
     Redis_instantaneous_ops_per_sec "gauge"
     Redis_rdb_bgsave_in_progress "gauge"
     Redis_total_commands_processed "counter"
     Redis_keyspace_hits "derive"
     Redis_keyspace_misses "derive"
     #Redis_master_repl_offset "gauge"
     #Redis_master_last_io_seconds_ago "gauge"
     #Redis_slave_repl_offset "gauge"
   </Module>
</Plugin>


The "disk" plugin issue was resolved, it was missing a package 
dependency which I installed.

this is what the log shows :

Oct 11 03:51:59 ic-01 collectd[32477]: Initialization complete, entering 
read-loop.
Oct 11 03:52:03 ic-01 collectd[32477]: Exiting normally.
Oct 11 03:52:03 ic-01 collectd[32477]: collectd: Stopping 5 read threads.
Oct 11 03:52:03 ic-01 collectd[32477]: collectd: Stopping 5 write threads.
Oct 11 03:52:03 ic-01 collectdmon[32476]: Info: collectd terminated with 
exit status 0
Oct 11 03:52:03 ic-01 collectdmon[32476]: Info: shutting down collectdmon
Oct 11 06:12:38 ic-01 collectd[38642]: Initialization complete, entering 
read-loop.
Oct 11 06:48:58 ic-01 collectd[38642]: Exiting normally.
Oct 11 06:48:58 ic-01 collectd[38642]: collectd: Stopping 5 read threads.
Oct 11 06:48:58 ic-01 collectd[38642]: collectd: Stopping 5 write threads.
Oct 11 06:48:58 ic-01 collectdmon[38641]: Info: collectd terminated with 
exit status 0
Oct 11 06:48:58 ic-01 collectdmon[38641]: Info: shutting down collectdmon
Oct 11 06:48:59 ic-01 collectd[39525]: Initialization complete, entering 
read-loop.
Oct 11 07:52:44 ic-01 collectd[39525]: Exiting normally.
Oct 11 07:52:44 ic-01 collectd[39525]: collectd: Stopping 5 read threads.
Oct 11 07:52:44 ic-01 collectd[39525]: collectd: Stopping 5 write threads.
Oct 11 07:52:44 ic-01 collectdmon[39524]: Info: collectd terminated with 
exit status 0
Oct 11 07:52:44 ic-01 collectdmon[39524]: Info: shutting down collectdmon
Oct 11 07:52:45 ic-01 collectd[40419]: Initialization complete, entering 
read-loop.
Oct 11 08:55:03 ic-01 collectd[40419]: Exiting normally.
Oct 11 08:55:03 ic-01 collectd[40419]: collectd: Stopping 5 read threads.
Oct 11 08:55:03 ic-01 collectd[40419]: collectd: Stopping 5 write threads.
Oct 11 08:55:03 ic-01 collectdmon[40418]: Info: collectd terminated with 
exit status 0
Oct 11 08:55:03 ic-01 collectdmon[40418]: Info: shutting down collectdmon
Oct 11 08:55:04 ic-01 collectd[1014]: Initialization complete, entering 
read-loop.

Hope this helps.



On 12/10/15 01:14, Garret Heaton wrote:
>
> Can you post your config?
>
> Also, because you're having issues with the |disk| plugin, perhaps 
> none of the plugins are being loaded and no data is being collected? I 
> don't remember how collectd behaves in this case.
>
>     oddly this plugin is not shipped with my version of collectd :
>     collectd-5.5.0.189
>
> Are you referring to this redis plugin? It's unofficial. See 
> https://collectd.org/wiki/index.php/Redis
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/powdahound/redis-collectd-plugin/issues/21#issuecomment-147250841>.
>


-- 
Assaf Flatto
Mobile: +44 (0)7527 055 681
Mobile - Israel: +972 (0)544 837 886
e-mail: assaf@aikilinux.com
Skype : aiki_linux
Website : http://www.aikilinux.com

**Comment by powdahound** [comment]
First off, I don't think you're even loading the plugin's configuration file. See the docs on [Include](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#include_path_pattern) and then make sure you add one that properly loads yours.

Hopefully that works, but if not:
1. Are you properly getting stats for other plugins?
2. Can you set the `LogLevel` to [debug](https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_syslog)?

**Comment by aflatto** [comment]
Hello Garret

You were right , the include statement was commented out , my mistake.

Once include was active and the file loaded, this was the output in the log:

Oct 13 02:08:52 dal09-ic-01 collectd[38455]: Unhandled python exception 
in read callback: KeyError: 'master_repl_offset'
Oct 13 02:08:52 dal09-ic-01 collectd[38455]: read-function of plugin 
`python.redis_info' failed. Will suspend it for 20.000 seconds.
Oct 13 02:09:12 dal09-ic-01 collectd[38455]: Unhandled python exception 
in read callback: KeyError: 'master_repl_offset'
Oct 13 02:09:12 dal09-ic-01 collectd[38455]: read-function of plugin 
`python.redis_info' failed. Will suspend it for 40.000 seconds.
Oct 13 02:09:52 dal09-ic-01 collectd[38455]: Unhandled python exception 
in read callback: KeyError: 'master_repl_offset'
Oct 13 02:09:52 dal09-ic-01 collectd[38455]: read-function of plugin 
`python.redis_info' failed. Will suspend it for 80.000 seconds.
Oct 13 02:11:12 dal09-ic-01 collectd[38455]: Unhandled python exception 
in read callback: KeyError: 'master_repl_offset'
Oct 13 02:11:12 dal09-ic-01 collectd[38455]: read-function of plugin 
`python.redis_info' failed. Will suspend it for 160.000 seconds.
Oct 13 02:13:52 dal09-ic-01 collectd[38455]: Unhandled python exception 
in read callback: KeyError: 'master_repl_offset'
Oct 13 02:13:52 dal09-ic-01 collectd[38455]: read-function of plugin 
`python.redis_info' failed. Will suspend it for 320.000 seconds.


Other Plugins are sending data with no issues .



On 12/10/15 17:44, Garret Heaton wrote:
>
> First off, I don't think you're even loading the plugin's 
> configuration file. See the docs on Include 
> <https://collectd.org/documentation/manpages/collectd.conf.5.shtml#include_path_pattern> 
> and then make sure you add one that properly loads yours.
>
> Hopefully that works, but if not:
> 1. Are you properly getting stats for other plugins?
> 2. Can you set the |LogLevel| to debug 
> <https://collectd.org/documentation/manpages/collectd.conf.5.shtml#plugin_syslog>?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/powdahound/redis-collectd-plugin/issues/21#issuecomment-147418812>.
>


-- 
Assaf Flatto
Mobile: +44 (0)7527 055 681
Mobile - Israel: +972 (0)544 837 886
e-mail: assaf@aikilinux.com
Skype : aiki_linux
Website : http://www.aikilinux.com

**Comment by powdahound** [comment]
Did you uncomment one of the `#Redis_master_repl_offset "gauge"` lines? Maybe the collectino of that stat is broken. If you get other errors like that I'd suggest comparing them to the list of fields you've configured the plugin to try to read. Perhaps some of them are not available in the version of redis you're using.

FWIW, this plugin isn't guaranteed to support specific versions of Redis. It isn't actively developed but is fixed every so often by users.
