### ISSUE TITLE
how to make collectd to run your plugin using python3

### ISSUE THREAD

**Issue by tkumark** [powdahound/redis-collectd-plugin#35]
I am trying to run your plugin. I am getting the following error
`Unhandled python exception in read callback: TypeError: makefile() got an unexpected keyword argument 'newline'`
This is because collectd python plugin is trying execute your script using python 2.7 instead of Python3. 
How can I force collectd to use Python 3 for the python plugin? I am trying to run this on amazon linux 2 ec2 instance

**Comment by powdahound** [comment]
Unfortunately I don't have a clear answer for you as I haven't used collectd with Python 3 before. I think your post in the collectd project (https://github.com/collectd/collectd/issues/4097) is a better place to ask. Good luck!

**Comment by tkumark** [comment]
@powdahound Sorry I do not understand/confused it is in your script redis_info.py in line 53 you call `fp = s.makefile('r', newline='\r\n')` `newline` was introduced in Python3. So how are you making it run with collectd?

**Comment by powdahound** [comment]
@tkumark Sorry for the confusion. The python3 syntax changes are much more recent than my last use of the plugin. See #33
